[package]
name = "dgc-decoder"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base45 = ""
flate2 = ""
serde_cbor = ""
serde = { version = "", features = [ "derive" ] }
serde_bytes = ""
